### ISSUE TITLE
Prometheus metrics are correctly labeled only for statefulesets

### ISSUE THREAD

**Issue by menardorama** [joshuarobinson/pso-analytics#1]
Hi,

First of all thank you for providing such tool that was lacking to monitor purestorage pvc.

I am currently trying to integrate on our prometheus stack (prom operator) and it seems that metrics are useful for statefulset but not for deployment.

I have lots of pvc that are not labeled and I can only see on which namespace they are defined.
Do you think it's feasable for you to add deployments as well ?

**Comment by joshuarobinson** [comment]
Hi Thomas,
Today tracking the Statefulset is easier, but I would be interested more in how you use deployments so that I can improve. The challenge I see is that the storage belongs to a PersistentVolumeClaim, not a specific deployment, and can in fact be shared amongst multiple deployments.

The way I approach it is to label each of my PVCs, like:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: graf-claim
  labels:
    app: grafana
spec:
  storageClassName: pure-file
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```
If you could provide more details about how your deployments use PVCs, I can figure out how to best help.
